apiVersion: v1
kind: Namespace
metadata:
  name: akssample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depweb
  namespace: akssample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: httpd
        name: aspnetapp
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svcweb
  namespace: akssample
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---